apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-feeds-service
  name: udagram-feeds-service-svc
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 5000
  selector:
    app: udagram-feeds-service

    