version: "3.0"
services:
  users:
    build: 
        context: ./udagram-services/user-service
    image: jdejesus11/udacity-aws:udagram-user-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=PROD
      - POSTGRES_USERNAME=udagram
      - POSTGRES_PASSWORD=Dragon1234
      - POSTGRES_HOST=udagram.ck9glbuovftc.us-west-2.rds.amazonaws.com
      - POSTGRES_DB=udagram
      - AWS_BUCKET=udagram-396242104882-dev
      - AWS_REGION=us-west-2
      - AWS_PROFILE=default
      - JWT_SECRET=#@.Dragon.#
      - PORT=3000
  feeds:
    build: 
        context: ./udagram-services/feed-service
    image: jdejesus11/udacity-aws:udagram-feed-service
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=PROD
      - POSTGRES_USERNAME=udagram
      - POSTGRES_PASSWORD=Dragon1234
      - POSTGRES_HOST=udagram.ck9glbuovftc.us-west-2.rds.amazonaws.com
      - POSTGRES_DB=udagram
      - AWS_BUCKET=udagram-396242104882-dev
      - AWS_REGION=us-west-2
      - AWS_PROFILE=default
      - JWT_SECRET=#@.Dragon.#
      - PORT=5000
  reverse-proxy:
    build: 
        context: ./udagram-services/reverse-proxy-service
    image: jdejesus11/udacity-aws:udagram-reverse-proxy-service
  app:
    build: 
        context: ./udagram-app
    image: jdejesus11/udacity-aws:udagram-app
