apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feeds-api 
  labels:
    app: udagram-feeds-api 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udagram-feeds-api 
  template:
    metadata:
      labels:
        app: udagram-feeds-api 
    spec:
      containers:
      - name:  udagram-feeds-api 
        image: jdejesus11/udacity-aws:udagram-feeds-api 
        ports:
        - containerPort: 8080
        livenessProbe:
         httpGet:
           path: /health
           port: 8080
         initialDelaySeconds: 3
         periodSeconds: 3

