apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-users-service
  labels:
    app: udagram-users-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udagram-users-service 
  template:
    metadata:
      labels:
        app: udagram-users-service 
    spec:
      containers:
      - name:  udagram-users-service 
        image: jdejesus11/udacity-aws:udagram-user-service
        ports:
        - containerPort: 3000
        livenessProbe:
         httpGet:
           path: /health
           port: 3000
         initialDelaySeconds: 3
         periodSeconds: 3

