apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-users-api 
  name: udagram-users-api-svc
spec:
  ports:
  - name: "8080"
    port: 80
    targetPort: 8080
  selector:
    app: udagram-users-api 

    