apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-users-services 
  name: udagram-users-services-svc
spec:
  ports:
  - name: "3000"
    port: 80
    targetPort: 3000
  selector:
    app: udagram-users-services