apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-reverse-proxy
  name: udagram-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: udagram-reverse-proxy
  template:
    metadata:
      labels:
        service: udagram-reverse-proxy
        name: udagram-reverse-proxy
    spec:
      containers:
      - image:  jdejesus11/udacity-aws:udagram-reverse-proxy-service
        name: udagram-reverse-proxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 80
      restartPolicy: Always